spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

dochelper:
  storage:
    enabled: false
  infrastructure:
    qdrant-health-enabled: false
